# https://github.com/marketplace/actions/publish-dart-flutter-package
name: pub publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
          
    steps:
      - uses: actions/checkout@v1
      - uses: sakebook/actions-flutter-pub-publisher@v1.4.0
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          skip_test: true
          flutter_package: true
          dry_run: false
