# https://github.com/marketplace/actions/dart-and-flutter-package-publisher
name: test

on:
  push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: 'publish'
        uses: k-paxian/dart-package-publisher@master
        with:
          # skipTests: true
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          dryRunOnly: true
          flutter: true
